FROM python:3.11-slim

# Primero instalar dependencias básicas del sistema
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gnupg2 \
    curl \
    apt-transport-https \
    gcc \
    g++ \
    libgssapi-krb5-2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Agregar repositorios de Microsoft y limpiar paquetes ODBC existentes
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg && \
    curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    apt-get remove -y unixodbc* odbcinst* && \
    apt-get autoremove -y

# Instalar controladores de Microsoft SQL Server
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools && \
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Instalar dependencias para Pillow (si usas ImageField)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /DaztlServer

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY DaztlServer/ .

EXPOSE 8000

COPY script.sh /script.sh
RUN chmod +x /script.sh

ENTRYPOINT ["/script.sh"]