FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y gnupg2 curl wget apt-transport-https && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

RUN wget -O /etc/apt/sources.list.d/mssql-release.list https://packages.microsoft.com/config/debian/11/prod.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev gcc && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /DaztlServer

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY DaztlServer/ .

EXPOSE 50051

CMD ["python", "daztl_rpc/server.py"]
